---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r}
library(tidyverse)
```
```{r}
load("MensScores2017 05 01.Rdata")
source('C:/Users/mr437799/Dropbox/Current/Data Projects/GitHub/ranking-basketball/MarginPredictionFromCenter.R')

#MOV of 6 is insurmountable
P=matrix(c(1   ,-1/2,0   ,0,0,0,0,0,0,0,0,
           -1/2,1   ,-1/2,0   ,0,0,0,0,0,0,0,
           0   ,-1/2,1   ,-1/2,0   ,0,0,0,0,0,0,
           0   ,0   ,-1/2,1   ,-1/2,0,0,0,0,0,0,
           0,0   ,0   ,-1/2,1   ,-1/2,0,0,0,0,0,
           0,0,0   ,0   ,-1/2,1   ,-1/2,0,0,0,0,
           0,0,0,0   ,0   ,-1/2,1   ,-1/2,0,0,0,
           0,0,0,0,0   ,0   ,-1/2,1   ,-1/2,0,0,
           0,0,0,0,0,0   ,0   ,-1/2,1   ,-1/2,0,
           0,0,0,0,0,0,0   ,0   ,-1/2,1   ,-1/2,
           0,0,0,0,0,0,0,0   ,0   ,-1/2,1   )
         ,nrow=11)
v=c(0,0,0,0,0,0,0,0,0,0,1/2)
shares<-solve(P,v)
```
```{r}
library(Matrix)
A=sparseMatrix(seq(1,length(teams$Team)),seq(1,length(teams$Team)),x=0)
b=rep(1,length(teams$Team))

for(i in 1:length(scores$Team1)){
  if(abs(scores[i,]$Score1-scores[i,]$Score2)>=6){
    if(scores[i,]$Score1>scores[i,]$Score2){
      Share1<-1
      Share2<-0
    } else{
      Share2<-1
      Share1<-0
    }
  } else{
    Share1<-shares[scores[i,]$Score1-scores[i,]$Score2+6]
    Share2<-1-Share1
  }
  team1=match(scores[i,]$Team1,teams$Team)
  team2=match(scores[i,]$Team2,teams$Team)
  if( is.na(team1) | is.na(team2) |length(team1)>1 | length(team2)>1){ 
    cat(scores[i,]$Team1, ":", team1, "\n",
        scores[i,]$Team2, ":", team2) 
    next }
  A[team1,team2]=
    A[team1,team2]+Share2
  A[team2,team1]=
    A[team2,team1]+Share1
  A[team1,team1]=
    A[team1,team1]+Share1
  A[team2,team2]=
    A[team2,team2]+Share2
}
#image(A)


A_unnormed <- A
for(i in 1:length(teams$Team)){
  if(sum(A[i,])!=0){ 
    A[i,]=A[i,]/sum(A[i,])
  }
}

library(expm)
#b=t(rep(1,length(teams$Team)))
e<-Re(eigen(t(A))$vectors[,1])
b<-e/sum(e)*length(e)
#for( i in 1:1000){
#  b<-b%*%A
#}

library(tidyverse)
teams$Index = 1:length(teams$Team)
rankedteams<-bind_cols(teams, tibble(Rating=as.numeric(b)))
rankedteams <-arrange(rankedteams, desc(Rating))

```

```{r}
#Atlantic Coast
rankedteams %>% filter(State %in% c("MD", "DE", "DC", "NC", "SC", "VA")) %>% select(Team, Index, Rating, Wins, Losses)
#Great Lakes
#rankedteams %>% filter(State %in% c("IL", "IN", "KY", "MI")) %>% select(Team, Index, Rating, Wins, Losses)
#New England
#rankedteams %>% filter(State %in% c("ME", "MA", "NH", "RI", "VT")) %>% select(Team, Index, Rating, Wins, Losses)
#South Central
#rankedteams %>% filter(State %in% c("AR", "CO", "KS", "MO", "OK", "TX", "WY")) %>% select(Team, Index, Rating, Wins, Losses)
#Southeast
# %>% filter(State %in% c("AL", "FL", "GA", "LA", "MS", "TN")) %>% select(Team, Index, Rating, Wins, Losses)


```

```{r}
bids <- 3
#Atlantic Coast Women
#indices <- c(284, 177, 77, 100, 176, 140, 178, 56, 83, 235, 96, 127, 150, 6, 267, 303)
#GReat Lakes women
#indices <- c(156, 188, 186, 121, 123, 50, 157, 215)
#New England Women
#indices<-c(73, 271, 281, 182, 22, 115, 166, 23, 158, 151)
#Southeast Women
#indices <- c(91, 101, 106, 134, 93, 14, 47, 89, 256, 278, 142, 2)
#South Central Women
#indices <- c(260, 62, 132, 63, 165, 291, 78, 64, 13, 262)
#Atlantic Coast Men
#indices <- c(293, 292, 294, 498, 474, 471, 206, 161, 245, 100, 159, 472, 383, 128, 136, 290)
#Great Lakes Men
indices <- c(256, 310, 346, 308, 193, 195, 91, 176, 217, 197, 258, 489 )
#New England Men
#indices <- c(249, 182, 453, 50, 302, 467, 37, 275, 39, 285, 353, 248, 451, 466, 48, 458)
#South Central Men
#indices <- c(112, 108, 436, 439, 443, 20, 322, 481, 437, 442, 366, 212, 300, 29, 213, 271)
#South East Men
#indices <- c(165, 87, 24, 147, 151, 233, 144, 171, 168, 428, 427, 385, 215, 269, 7,5  )
e<-Re(eigen(t(A))$vectors[,1])
e<-e/sum(e)*length(e)
# possibleTeams <-indices[1:bids]
# cat(possibleTeams, " ")
# team <-bids+1
# possible =TRUE
# while(possible){
#   if(Predict_Margin(A_unnormed, c(0,shares,1),
#                     indices[team],possibleTeams[bids], e)>-4 ){
#     possibleTeams <- indices[1:team]
#     cat(possibleTeams[team], " ")
#     team=team+1
#     if(team > length(indices)){
#       possible = FALSE
#     }
#   } else{
#     possible = FALSE
#   }
# }
teams$Team[indices]
```
```{r}

MOV=diag(rep(0,length(indices)))
for( i in 1:(length(indices)-1)){
  for(j in (i+1):length(indices)){
    MOV[i,j]= Predict_Margin(A_unnormed , c(0,shares,1), indices[j], indices[i], e)
    cat(teams$Team[indices[i]]," ", teams$Team[indices[j]], ":", MOV[i,j], "\n")
    MOV[j,i]=-MOV[i,j]
  }
}


```


```{r}
MOV=diag(rep(0,length(possibleTeams)))
for( i in 1:(length(possibleTeams)-1)){
  for(j in (i+1):length(possibleTeams)){
    MOV[i,j]= Predict_Margin(A_unnormed , c(0,shares,1), possibleTeams[j], possibleTeams[i])
    cat(teams$Team[possibleTeams[i]]," ", teams$Team[possibleTeams[j]], ":", MOV[i,j], "\n")
    MOV[j,i]=-MOV[i,j]
  }
}


```

```{r }
rownames(MOV) <-teams$Team[indices]
colnames(MOV) <-teams$Team[indices]
print(xtable::xtable(MOV), type="html")
#MOV

```