---
title: "Print Tables"
author: "Matt Rissler, PhD"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message =  FALSE)
library(tidyverse)
library(readr)
library(stringr)
date="2019 09 23"
#old_date="2017 09 19"
```

# Men

## Club

```{r MenClub, echo=FALSE, results="asis"}
Ranking <- read_csv(paste0("USAU Club Men RW",date,".csv"))
#oldRanking <- read_csv(paste0("USAU Club Men RW",old_date,".csv"))

#Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#  mutate(Rank.diff = Rank.y-Rank.x) %>%
#  select(Rank.x, Rank.diff,  Team, contains(".x"), City, State) %>%
#  rename( Rank=Rank.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()

```

## Masters
```{r MenMasters, results='asis', echo=FALSE}
Ranking <- read_csv(paste0("USAU Masters Men RW",date,".csv"))
#oldRanking <- read_csv("USAU College Men RW2017 05 22.csv")

#Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#  mutate(Rank.diff = Rank.y-Rank.x, Rating.diff=Rating.y-Rating.x) %>%
#  select(Ranking.x, Ranking.diff, Rating.diff, Team, contains(".x"), City, State) %>%
#  rename( Ranking=Ranking.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()
```


## Grand Masters

```{r Men GM, results='asis', echo=FALSE}
Ranking <- read_csv(paste0("USAU Grand Masters Men RW",date,".csv"))
#oldRanking <- read_csv("USAU College Men RW2017 05 22.csv")

#Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#  mutate(Rank.diff = Rank.y-Rank.x, Rating.diff=Rating.y-Rating.x) %>%
#  select(Ranking.x, Ranking.diff, Rating.diff, Team, contains(".x"), City, State) %>%
#  rename( Ranking=Ranking.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()

```


# Women

## Club



```{r WomenClub, echo=FALSE, results="asis"}
date="2019 09 24"
Ranking <- read_csv(paste0("USAU Club Women RW",date,".csv"), 
    locale = locale(encoding = "ISO-8859-1", 
        asciify = TRUE))

# oldRanking <- read_csv(paste0("USAU Club Women RW",old_date,".csv"))
# 
# Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#   mutate(Rank.diff = Rank.y-Rank.x) %>%
#  select(Rank.x, Rank.diff, Team, contains(".x"), City, State) %>%
#   rename( Rank=Rank.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% 
  #mutate(City =  if_else(str_detect(City,"Qu"),"Quebec",City) )%>%
  knitr::kable()
```

## Masters
```{r WomenMasters, results='asis', echo=FALSE}
Ranking <- read_csv(paste0("USAU Masters Women RW",date,".csv"))
#oldRanking <- read_csv("USAU College Men RW2017 05 22.csv")

#Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#  mutate(Rank.diff = Rank.y-Rank.x, Rating.diff=Rating.y-Rating.x) %>%
#  select(Ranking.x, Ranking.diff, Rating.diff, Team, contains(".x"), City, State) %>%
#  rename( Ranking=Ranking.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()
```

## Grand Masters

```{r WomenGrandMasters, results='asis', echo=FALSE}
Ranking <- read_csv(paste0("USAU Grand Masters Women RW",date,".csv"))
#oldRanking <- read_csv("USAU College Men RW2017 05 22.csv")

#Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#  mutate(Rank.diff = Rank.y-Rank.x, Rating.diff=Rating.y-Rating.x) %>%
#  select(Ranking.x, Ranking.diff, Rating.diff, Team, contains(".x"), City, State) %>%
#  rename( Ranking=Ranking.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()
```

# Mixed

## Club

```{r MixedClub, results='asis', echo=FALSE}
Ranking <- read_csv(paste0("USAU Club Mixed RW",date,".csv"))
# oldRanking <- read_csv(paste0("USAU Club Mixed RW",old_date,".csv"))
# 
# Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#   mutate(Rank.diff = Rank.y-Rank.x) %>%
#   select(Rank.x, Rank.diff, Team, contains(".x"), City, State) %>%
#   rename( Rank=Rank.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()



```


## Masters

```{r MixedMasters, results='asis', echo=FALSE}
Ranking <- read_csv(paste0("USAU Masters Mixed RW",date,".csv"))
#oldRanking <- read_csv("USAU College Men RW2017 05 22.csv")

#Ranking <- left_join(Ranking,oldRanking,by=c("Team", "City", "State")) %>% 
#  mutate(Rank.diff = Rank.y-Rank.x, Rating.diff=Rating.y-Rating.x) %>%
#  select(Ranking.x, Ranking.diff, Rating.diff, Team, contains(".x"), City, State) %>%
#  rename( Ranking=Ranking.x, Rating=Rating.x, Wins=Wins.x, Losses=Losses.x)

Ranking %>% head(25) %>% knitr::kable()
```